<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="WIB-DES-00567" ignored="2" name="functional test" tests="3" failures="2" timestamp="14 Nov 2017 12:44:30 GMT" time="0.301" errors="0">
  <testcase name="Login_001" time="0.005" classname="DataDriving.Login_001">
    <failure type="java.lang.AssertionError" message="expected [Login with valid credentials] but found [Login_001]">
      <![CDATA[java.lang.AssertionError: expected [Login with valid credentials] but found [Login_001]
	at DataDriving.Login_001.Login_001(Login_001.java:27)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- Login_001 -->
  <testcase name="Login_002" time="0.001" classname="DataDriving.Login_002"/>
  <testcase name="Login_003" time="0.001" classname="DataDriving.Login_003">
    <failure type="java.lang.AssertionError" message="expected [Login with blank credentials] but found [Login_003]">
      <![CDATA[java.lang.AssertionError: expected [Login with blank credentials] but found [Login_003]
	at DataDriving.Login_003.Login_003(Login_003.java:27)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- Login_003 -->
  <testcase name="@BeforeSuite initOnce" time="0.0" classname="DataDriving.BaseClass">
    <ignored/>
  </testcase> <!-- @BeforeSuite initOnce -->
  <testcase name="@BeforeSuite initOnce" time="0.0" classname="DataDriving.BaseClass">
    <ignored/>
  </testcase> <!-- @BeforeSuite initOnce -->
</testsuite> <!-- functional test -->
